#ifndef PROMPT_H
#define PROMPT_H

#include <iostream>
#include "stdlib.h"
#include "QString"

using namespace std;

enum Voice {UNIT_OK, UNIT_FAILED, CHANGE_BATTERIES, STAY_CALM, CHECK_RESPONSIVENESS, CALL_FOR_HELP, OPEN_AIRWAY, CHECK_BREATHING, GIVE_TWO_BREATHS, PLUG_IN_CABLE, ATTACH_DEFIB,
            CHECK_PADS, ADULT_PADS, PEDIATRIC_PADS, DONT_TOUCH, SHOCK_ADVISED, NO_SHOCK_ADVISED, KEEP_PATIENT_STILL, CANNOT_DELIVER_SHOCK, DELIVERING_SHOCK, SHOCK_DELIVERED, START_CPR, CONTINUE_CPR,
           PUSH_HARDER, GOOD_COMPRESSIONS, STOP_CPR, IF_NEW_BATTERIES, NON_RESCUE, COMMUNICATIONS, AMBULANCE_ARRIVES, NORMAL_RHYTHM, NEW_BATTERIES, OFF};

class Prompt
{
public:
    Prompt();

    QString playVoicePrompt(Voice);
};

#endif // PROMPT_H
